$ANSIBLE_VAULT;1.1;AES256
63303434393039383634333435336266633466643764613334316161656537363965616235643562
6130303438383939303934313164613564386534646463650a326430396264613237303237313330
31303734663832396235613066336438363235383265306131666437366632313230346362346361
3436326566303536660a366334303737636238643531376264366333313336633262333161653962
32363336346539316236393964633634363764313135326134666434346534656566353137363364
39343061343133386534306433373966643061626330336432376536346262646333633465613539
656539663863353766623862373431636434
